<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANUKIRAN" failures="1" tests="6" name="testCase.LogInPageTest" time="18.290" errors="0" timestamp="2024-10-28T11:35:58 EDT" skipped="5">
  <testcase classname="testCase.LogInPageTest" name="verifyLogInWithValidData" time="5.080">
    <skipped/>
  </testcase> <!-- verifyLogInWithValidData -->
  <testcase classname="testCase.LogInPageTest" name="verifyLogInWithValidData" time="4.473">
    <failure message="SignIn text not as expected expected [7rmart supermarket1] but found [7rmart supermarket]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: SignIn text not as expected expected [7rmart supermarket1] but found [7rmart supermarket]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testCase.LogInPageTest.verifyLogInWithValidData(LogInPageTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyLogInWithValidData -->
  <testcase classname="testCase.LogInPageTest" name="verifyLogInWithValidData" time="4.379">
    <skipped/>
  </testcase> <!-- verifyLogInWithValidData -->
  <testcase classname="testCase.LogInPageTest" name="verifyLogInWithValidData" time="4.358">
    <skipped/>
  </testcase> <!-- verifyLogInWithValidData -->
  <testcase classname="testCase.LogInPageTest" name="verifyLogInWithInValidData">
    <skipped/>
  </testcase> <!-- verifyLogInWithInValidData -->
  <testcase classname="testCase.LogInPageTest" name="verifyLogInWithExcelData">
    <skipped/>
  </testcase> <!-- verifyLogInWithExcelData -->
</testsuite> <!-- testCase.LogInPageTest -->
